import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Breadcrumbs from '@mui/material/Breadcrumbs'
import Link from '@mui/material/Link'
import Typography from '@mui/material/Typography'
import BreadCrumbs from '@/components/etc/BreadCrumbs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main className='bg-slate-300 min-h-screen min-w-screen text-black'>
        <BreadCrumbs/>
          {children}
        </main>
      </body>
    </html>
  )
}
